"""Shared test doubles and fixtures.

**Owned by the integrator.  OFF-LIMITS to module agents** (contract §12).  If you
need a variant, build it locally in your own test file or request the change in your
report — do not edit this file.

The important piece here is :func:`make_wechat_notify`: it builds a *genuinely*
RSA-SHA256 signed and *genuinely* AES-256-GCM encrypted WeChat Pay callback from a
throwaway keypair.  Without it the payment path is only testable against a mock that
would happily accept a forged body.
"""

from __future__ import annotations

import base64
import hashlib
import hmac
import json
import secrets
import uuid
from dataclasses import dataclass, field
from datetime import UTC, datetime
from pathlib import Path

from cryptography.hazmat.primitives import hashes, serialization
from cryptography.hazmat.primitives.asymmetric import padding, rsa
from cryptography.hazmat.primitives.ciphers.aead import AESGCM

from app.config import Settings
from app.ports.calendar import BusyInterval, CalendarEvent
from app.ports.payments import ChargeRequest, ChargeResult, PaymentNotification
from app.ports.payments import PaymentSignatureError

# ---------------------------------------------------------------------------
# Calendar
# ---------------------------------------------------------------------------


@dataclass
class FakeCalendarGateway:
    """In-memory calendar.

    ``busy`` holds the pre-existing commitments.  A hold created through
    :meth:`create_hold` also becomes busy, which is what makes the
    "a slot already held is not offered" test meaningful.
    """

    busy: list[BusyInterval] = field(default_factory=list)
    events: dict[str, dict] = field(default_factory=dict)
    released: list[str] = field(default_factory=list)
    confirmed: list[str] = field(default_factory=list)
    _counter: int = 0

    def freebusy(self, time_min: datetime, time_max: datetime) -> list[BusyInterval]:
        return [
            interval
            for interval in self.busy
            if interval.start < time_max and interval.end > time_min
        ]

    def create_hold(
        self,
        *,
        summary: str,
        description: str,
        start: datetime,
        end: datetime,
        reference: str,
    ) -> CalendarEvent:
        self._counter += 1
        event_id = f"evt-{self._counter:04d}"
        self.events[event_id] = {
            "summary": summary,
            "description": description,
            "start": start,
            "end": end,
            "reference": reference,
            "status": "tentative",
        }
        self.busy.append(BusyInterval(start=start, end=end))
        return CalendarEvent(event_id=event_id, html_link=f"https://cal.example/{event_id}")

    def confirm(self, event_id: str, *, summary: str, description: str) -> None:
        if event_id not in self.events:
            raise KeyError(f"unknown event {event_id}")
        self.events[event_id].update(
            summary=summary, description=description, status="confirmed"
        )
        self.confirmed.append(event_id)

    def release(self, event_id: str) -> None:
        # Idempotent on purpose: releasing an unknown event is not an error.
        event = self.events.pop(event_id, None)
        self.released.append(event_id)
        if event is not None:
            self.busy = [
                interval
                for interval in self.busy
                if not (interval.start == event["start"] and interval.end == event["end"])
            ]

    # convenience for tests
    def add_busy(self, start: datetime, end: datetime) -> None:
        self.busy.append(BusyInterval(start=start, end=end))


# ---------------------------------------------------------------------------
# Payments
# ---------------------------------------------------------------------------


@dataclass
class FakePaymentGateway:
    """HMAC-signed stand-in for WeChat Pay.

    ``parse_notification`` verifies ``X-Fake-Signature`` =
    ``hex(hmac_sha256(secret_key, body))`` before returning anything, so it fails
    closed in the same *shape* as the real adapter.  Use
    :meth:`build_notify` to construct a valid callback.
    """

    secret_key: str = "dev-only-change-me"
    charges: list[ChargeRequest] = field(default_factory=list)
    closed: list[str] = field(default_factory=list)
    orders: dict[str, PaymentNotification] = field(default_factory=dict)
    fail_create: bool = False

    def create_charge(self, req: ChargeRequest) -> ChargeResult:
        if self.fail_create:
            raise RuntimeError("fake payment gateway configured to fail")
        self.charges.append(req)
        return ChargeResult(
            code_url=f"weixin://wxpay/bizpayurl?pr=FAKE{req.out_trade_no}",
            provider_order_id=f"fake-{req.out_trade_no}",
        )

    def parse_notification(
        self, headers: dict[str, str], body: bytes
    ) -> PaymentNotification:
        lowered = {k.lower(): v for k, v in headers.items()}
        signature = lowered.get("x-fake-signature", "")
        expected = hmac.new(
            self.secret_key.encode("utf-8"), body, hashlib.sha256
        ).hexdigest()
        if not hmac.compare_digest(signature, expected):
            raise PaymentSignatureError("bad fake signature")

        payload = json.loads(body.decode("utf-8"))
        notification = PaymentNotification(
            out_trade_no=payload["out_trade_no"],
            transaction_id=payload["transaction_id"],
            amount_fen=payload["amount_fen"],
            trade_state=payload.get("trade_state", "SUCCESS"),
            success_time=payload.get("success_time"),
        )
        self.orders[notification.out_trade_no] = notification
        return notification

    def query_order(self, out_trade_no: str) -> PaymentNotification | None:
        return self.orders.get(out_trade_no)

    def close_order(self, out_trade_no: str) -> None:
        self.closed.append(out_trade_no)

    def build_notify(
        self,
        *,
        out_trade_no: str,
        amount_fen: int,
        transaction_id: str | None = None,
        trade_state: str = "SUCCESS",
        success_time: datetime | None = None,
    ) -> tuple[dict[str, str], bytes]:
        """A valid, correctly signed callback for this gateway."""
        body = json.dumps(
            {
                "out_trade_no": out_trade_no,
                "transaction_id": transaction_id or f"FAKE{uuid.uuid4().hex[:16]}",
                "amount_fen": amount_fen,
                "trade_state": trade_state,
                "success_time": (
                    success_time or datetime.now(UTC)
                ).isoformat(),
            }
        ).encode("utf-8")
        signature = hmac.new(
            self.secret_key.encode("utf-8"), body, hashlib.sha256
        ).hexdigest()
        return {"X-Fake-Signature": signature}, body


# ---------------------------------------------------------------------------
# Email
# ---------------------------------------------------------------------------


@dataclass
class RecordingEmailSender:
    sent: list[dict] = field(default_factory=list)
    fail: bool = False

    def send(self, *, to: str, subject: str, body: str) -> None:
        if self.fail:
            raise RuntimeError("fake email sender configured to fail")
        self.sent.append({"to": to, "subject": subject, "body": body})


# ---------------------------------------------------------------------------
# WeChat Pay: a real signed + encrypted callback, built from a throwaway keypair
# ---------------------------------------------------------------------------

WECHAT_API_V3_KEY = "0123456789abcdef0123456789abcdef"  # exactly 32 chars


@dataclass(frozen=True)
class WechatTestKeys:
    api_v3_key: str
    serial_no: str  # merchant apiclient_cert serial number
    public_key_id: str  # Wechatpay-Serial value on inbound notifications
    private_key_pem: str  # platform private key — signs notifications
    private_key_path: Path  # merchant apiclient_key.pem
    public_key_path: Path  # 微信支付公钥 — inbound verification


def make_wechat_keys(tmp_path: Path) -> WechatTestKeys:
    """Two throwaway RSA keypairs: one merchant, one "platform"."""
    tmp_path.mkdir(parents=True, exist_ok=True)

    merchant_key = rsa.generate_private_key(public_exponent=65537, key_size=2048)
    merchant_pem = merchant_key.private_bytes(
        encoding=serialization.Encoding.PEM,
        format=serialization.PrivateFormat.PKCS8,
        encryption_algorithm=serialization.NoEncryption(),
    )
    private_key_path = tmp_path / "apiclient_key.pem"
    private_key_path.write_bytes(merchant_pem)

    platform_key = rsa.generate_private_key(public_exponent=65537, key_size=2048)
    platform_pem = platform_key.private_bytes(
        encoding=serialization.Encoding.PEM,
        format=serialization.PrivateFormat.PKCS8,
        encryption_algorithm=serialization.NoEncryption(),
    )
    public_key_path = tmp_path / "pub_key.pem"
    public_key_path.write_bytes(
        platform_key.public_key().public_bytes(
            encoding=serialization.Encoding.PEM,
            format=serialization.PublicFormat.SubjectPublicKeyInfo,
        )
    )

    return WechatTestKeys(
        api_v3_key=WECHAT_API_V3_KEY,
        serial_no="4D2B4A1E5C6F7A8B9C0D1E2F3A4B5C6D7E8F9A0B",
        public_key_id="PUB_KEY_ID_TEST_0001",
        private_key_pem=platform_pem.decode("utf-8"),
        private_key_path=private_key_path,
        public_key_path=public_key_path,
    )


def wechat_settings(keys: WechatTestKeys, **overrides) -> Settings:
    """A ``Settings`` instance wired to the throwaway keys.

    Constructed directly (not via ``get_settings()``) so it never touches the
    lru_cached singleton the rest of the app uses.
    """
    values = {
        "app_env": "dev",
        "database_url": "sqlite://",
        "secret_key": "test-secret-key",
        "public_base_url": "http://testserver",
        "default_timezone": "Asia/Shanghai",
        "calendar_gateway": "fake",
        "payment_gateway": "wechat",
        "wechat_app_id": "wxtest000000000001",
        "wechat_mch_id": "1900000001",
        "wechat_api_v3_key": keys.api_v3_key,
        "wechat_cert_serial_no": keys.serial_no,
        "wechat_private_key_path": str(keys.private_key_path),
        "wechat_public_key_id": keys.public_key_id,
        "wechat_public_key_path": str(keys.public_key_path),
        "email_backend": "console",
    }
    values.update(overrides)
    return Settings(**values)


def wechat_notify_plaintext(
    *,
    out_trade_no: str,
    transaction_id: str,
    amount_fen: int,
    trade_state: str = "SUCCESS",
    success_time: datetime | None = None,
    currency: str = "CNY",
) -> dict:
    """The decrypted ``transaction`` object WeChat puts inside ``resource``."""
    moment = success_time or datetime.now(UTC)
    return {
        "mchid": "1900000001",
        "appid": "wxtest000000000001",
        "out_trade_no": out_trade_no,
        "transaction_id": transaction_id,
        "trade_type": "NATIVE",
        "trade_state": trade_state,
        "trade_state_desc": "支付成功" if trade_state == "SUCCESS" else trade_state,
        "bank_type": "OTHERS",
        "success_time": moment.strftime("%Y-%m-%dT%H:%M:%S+08:00"),
        "payer": {"openid": "oUpF8uMuAJO_M2pxb1Q9zNjWeS6o"},
        "amount": {
            "total": amount_fen,
            "payer_total": amount_fen,
            "currency": currency,
            "payer_currency": currency,
        },
    }


def make_wechat_notify(
    *,
    keys: WechatTestKeys,
    out_trade_no: str,
    amount_fen: int,
    transaction_id: str | None = None,
    trade_state: str = "SUCCESS",
    success_time: datetime | None = None,
    event_type: str = "TRANSACTION.SUCCESS",
    timestamp: int | None = None,
    nonce: str | None = None,
    tamper_body: bool = False,
    tamper_signature: bool = False,
    bad_serial: bool = False,
    omit_signature: bool = False,
) -> tuple[dict[str, str], bytes]:
    """Build a genuinely signed, genuinely encrypted WeChat Pay notification.

    Returns ``(headers, raw_body)`` ready to hand to
    ``WechatPayGateway.parse_notification`` (or to ``TestClient.post``).

    The tampering switches exist so a test can prove the adapter *fails closed*
    rather than merely asserting that the happy path works.
    """
    transaction_id = transaction_id or f"4200001{uuid.uuid4().hex[:14]}"
    timestamp = timestamp if timestamp is not None else int(datetime.now(UTC).timestamp())
    nonce = nonce or secrets.token_hex(8)

    plaintext = json.dumps(
        wechat_notify_plaintext(
            out_trade_no=out_trade_no,
            transaction_id=transaction_id,
            amount_fen=amount_fen,
            trade_state=trade_state,
            success_time=success_time,
        )
    ).encode("utf-8")

    associated_data = "transaction"
    aesgcm = AESGCM(keys.api_v3_key.encode("utf-8"))
    ciphertext = aesgcm.encrypt(
        nonce.encode("utf-8"), plaintext, associated_data.encode("utf-8")
    )

    envelope = {
        "id": str(uuid.uuid4()),
        "create_time": datetime.now(UTC).strftime("%Y-%m-%dT%H:%M:%S+08:00"),
        "resource_type": "encrypt-resource",
        "event_type": event_type,
        "summary": "支付成功",
        "resource": {
            "original_type": "transaction",
            "algorithm": "AEAD_AES_256_GCM",
            "ciphertext": base64.b64encode(ciphertext).decode("ascii"),
            "associated_data": associated_data,
            "nonce": nonce,
        },
    }
    raw_body = json.dumps(envelope, ensure_ascii=False).encode("utf-8")

    signature = _sign_notification(
        private_key_pem=keys.private_key_pem,
        timestamp=timestamp,
        nonce=nonce,
        body=raw_body,
    )

    if tamper_body:
        # Flip a byte in the ciphertext but keep the signature over the original
        # body — exactly what an attacker in the middle would produce.
        mutated = json.loads(raw_body.decode("utf-8"))
        original = mutated["resource"]["ciphertext"]
        mutated["resource"]["ciphertext"] = base64.b64encode(
            bytes([base64.b64decode(original)[0] ^ 0xFF]) + base64.b64decode(original)[1:]
        ).decode("ascii")
        raw_body = json.dumps(mutated, ensure_ascii=False).encode("utf-8")

    if tamper_signature:
        signature = base64.b64encode(b"not-a-real-signature" * 4).decode("ascii")

    headers = {
        "Wechatpay-Timestamp": str(timestamp),
        "Wechatpay-Nonce": nonce,
        "Wechatpay-Serial": "UNKNOWN_SERIAL_0000" if bad_serial else keys.public_key_id,
    }
    if not omit_signature:
        headers["Wechatpay-Signature"] = signature

    return headers, raw_body


def _sign_notification(
    *, private_key_pem: str, timestamp: int, nonce: str, body: bytes
) -> str:
    """RSA-SHA256 over ``f"{timestamp}\\n{nonce}\\n{body}\\n"``, base64 encoded."""
    from cryptography.hazmat.primitives.serialization import load_pem_private_key

    key = load_pem_private_key(private_key_pem.encode("utf-8"), password=None)
    message = f"{timestamp}\n{nonce}\n{body.decode('utf-8')}\n".encode("utf-8")
    signature = key.sign(message, padding.PKCS1v15(), hashes.SHA256())
    return base64.b64encode(signature).decode("ascii")
