"""Gateway wiring.  Owned by the integrator; module agents do not edit this file.

Every factory imports its adapter *inside the function body* so the application boots
even when an adapter module has not been written yet (contract §4).
"""

from __future__ import annotations

from functools import lru_cache

from app.config import settings
from app.ports.calendar import CalendarGateway
from app.ports.email import EmailSender
from app.ports.payments import PaymentGateway


@lru_cache
def get_calendar_gateway() -> CalendarGateway:
    kind = settings.calendar_gateway
    if kind == "fake":
        from app.adapters.calendar_fake import FakeCalendarGateway

        return FakeCalendarGateway()
    if kind == "google":
        from app.adapters.calendar_google import GoogleCalendarGateway

        return GoogleCalendarGateway()
    if kind == "relay":
        from app.adapters.calendar_relay import RelayCalendarGateway

        return RelayCalendarGateway()
    raise RuntimeError(f"unknown CALENDAR_GATEWAY: {kind!r}")


@lru_cache
def get_payment_gateway() -> PaymentGateway:
    kind = settings.payment_gateway
    if kind == "fake":
        from app.adapters.payments_fake import FakePaymentGateway

        return FakePaymentGateway()
    if kind == "wechat":
        from app.adapters.payments_wechat import WechatPayGateway

        return WechatPayGateway()
    raise RuntimeError(f"unknown PAYMENT_GATEWAY: {kind!r}")


@lru_cache
def get_email_sender() -> EmailSender:
    kind = settings.email_backend
    if kind == "console":
        from app.adapters.email_console import ConsoleEmailSender

        return ConsoleEmailSender()
    if kind == "smtp":
        from app.adapters.email_smtp import SmtpEmailSender

        return SmtpEmailSender()
    raise RuntimeError(f"unknown EMAIL_BACKEND: {kind!r}")
